name: ci
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python - << 'PY'
from importlib import import_module
import_module('streamlit')
import_module('pandas')
# Ensure app imports cleanly
import app
print('App import OK')
PY